name: journal-club
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - rise
  - pip
  - seaborn
  - jupyter_contrib_nbextensions
  - ffmpeg
  - pip:
      - tensorflow
      - tensorflow_probability
      - scikit-learn
